name: Budzik Aplikacji

on:
  schedule:
    # Uruchamiaj co 30 minut
    - cron: '*/30 * * * *'
  workflow_dispatch: # Pozwala uruchomić ręcznie przyciskiem

jobs:
  wake_up_job:
    runs-on: ubuntu-latest
    steps:
      - name: Pobudka!
        # Poniżej Twój link - bot wejdzie na stronę, żeby ją obudzić
        run: curl -s https://kalkulator-borntobrand.streamlit.app/ > /dev/null
